osx_image: xcode10.2
language: objective-c

xcode_scheme: Staging
xcode_project: pillarwallet.xcodeproj
#podfile: /Users/travis/build/pillarwallet/pillarwallet/ios/Podfile

before_install:
  - sudo pip install awscli
  - cd $TRAVIS_BUILD_DIR
  - chmod +x build-upload.sh
  - openssl aes-256-cbc -K $encrypted_e0de80b8e64f_key -iv $encrypted_e0de80b8e64f_iv -in travis_ci_key.enc -out travis_ci_key -d
  - touch /Users/travis/build/pillarwallet/pillarwallet/buildNumber.txt

jobs:
  include:
    - stage: build-and-upload
      script: ./build-upload.sh

stages:
  - name: build-and-upload
    if: branch = chore/ios_swift_version_increase4.2
